import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // style={{ background: "linear-gradient(180deg, #000000 36.4%, #191E2A 100%)" }}
        //  className={inter.className}
        className="overflow-x-hidden"
      >
        {children}
      </body>
    </html>
  );
}
